logging:
    level: INFO
http:
  connectorType: nonblocking+ssl
  port: 8443
  ssl:
      #Example is using a java keystore in the target directory.
      keyStore: ${ssl.cert.dir}/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType: pkcs12
