logging:
    level: INFO
http:
  connectorType: nonblocking+ssl
  port: 8443
  ssl:
      #This ZApp is using a java keystore in the target directory.
      keyStore: ./target/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType: pkcs12